In [3]:
import numpy as np
A = np.array([[0,1],
              [2,3],
              [4,5]])
B = np.array([[0,1,2,3],
              [4,5,6,7]])

In [4]:
answer=np.dot(A,B)

In [5]:
print(answer)
print(answer.max())

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
